### ISSUE TITLE
Source for pin headers

### ISSUE THREAD

**Issue by olkang** [scrapcomputing/486SocketBlaster#3]
Hi ScrapComputing,

I couldn't find another way to contact you with a question that wasn't youtube. I'm trying to source the pin headers but my google search skills must be week. Could you possibly link to a supplier's product page for them? 

Also thanks again for all your work and have you thought about setting up a patreon page?

**Comment by scrapcomputing** [comment]
Hi olkang,

I think I got mine on ebay long time ago, but I just checked and such headers show up on both ebay and amazon. Just use keywords like "round headers 2.54mm" and you will find them (you can also find them in male/female pairs). Most sellers list images with detailed dimensions, so just make sure that the male header pin diameter is 0.50mm at the bottom (that will face the motherboard socket) and 0.60mm at the top (this will get soldered onto the PCB, the drill hole is 0.67mm). 
So here is the thing about the female header. In the instructions I list the female header diameter as as 0.50mm (this is what was shown on the ebay seller's listing), but I just measured it with my calipers and it measures 0.54mm, so it must be a 0.55mm part, which is the most common size from what I can see. The drill hole size in the PCB is 0.57mm so there is a chance that the 0.55mm part won't fit if the tolerance is too high.

So here is what I will do. I will increase the hole size to 0.62mm so that they will fit the 0.55mm since this is the most common pin diameter for the female headers. Stay tuned for an updated PCB.

**Comment by scrapcomputing** [comment]
I updated the PCB, please check out rev 0.4. This revision should fit nicely female headers with a 0.55mm pin diameter.

**Comment by olkang** [comment]
Very cool, I've got what I believe are the correct pin sets on order through alieexpress. Once they come in I'll get a round of boards made.

Thanks again!
