### ISSUE TITLE
Allow for usage of available 168-pin sockets

### ISSUE THREAD

**Issue by megatog615** [scrapcomputing/486SocketBlaster#5]
It is possible to purchase 168-pin sockets [online](https://www.peconnectors.com/sockets-pga-cpu-and-memory/hws6934/). Perhaps the pcb could be redesigned to make use of them as a way to make the assembly easier? I have already considered buying one to use as a guide to hold pins in place for soldering, but I was wondering if it would not just be better to use them in the design.

**Comment by scrapcomputing** [comment]
We can't use a socket with the current design because it makes it impossible to solder it with a soldering iron: If we solder the socket then we can't solder the pins because they will be covered by the socket. If instead we solder the bottom pins first, then the pins will cover the pads se we won't be able to solder the socket.

So using a socket would require a complete redesign of the board, perhaps splitting it into two sections, or would require some fancy soldering techniques.
